### PR TITLE
fix: lock navigation bar

### LINKED ISSUE #115: Lock navigation bar

### PR DESCRIPTION
**Pull request by junlong4321**
Resolves #115

### CODE REVIEW

File: frontend/src/layouts/SidebarLayout.tsx [hunk 1]
```diff
@@ -5,12 +5,19 @@ import { NavigationBar } from "../components/NavigationBar";
...
+      <Grid item sx={{ width: "200px" }}>
         <NavigationBar />
       </Grid>
       <Divider orientation="vertical" flexItem sx={{ mr: "-1px" }} />
-      <Grid item xs={10} sx={{ backgroundColor: "secondary.light" }}>
+      <Grid
+        item
+        sx={{
+          backgroundColor: "secondary.light",
+          p: "2%",
```
Comment (dextertanyj) [inline frontend/src/layouts/SidebarLayout.tsx:17]: Helps to screen to look more consistent across different sizes.
```suggestion
          p: 3,
```

File: frontend/src/layouts/SidebarLayout.tsx [hunk 2]
```diff
@@ -5,12 +5,19 @@ import { NavigationBar } from "../components/NavigationBar";
 
 export const SidebarLayout = () => {
   return (
-    <Grid container>
-      <Grid item xs={2}>
+    <Grid container wrap="nowrap">
+      <Grid item sx={{ width: "200px" }}>
         <NavigationBar />
       </Grid>
       <Divider orientation="vertical" flexItem sx={{ mr: "-1px" }} />
```
Comment (dextertanyj) [inline frontend/src/layouts/SidebarLayout.tsx:12]: The divider seems unnecessary? The negative margin makes it not render on my screen at all.

**Review by dextertanyj — COMMENTED** [review]
Just some minor comments.

**Review by dextertanyj — APPROVED** [review]
